name: biblioteca97
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0  # Agrega esta línea si no está
  shared_preferences: ^2.0.15  # Verifica la última versión
  cupertino_icons: ^1.0.8
  http: ^0.13.6  # <-- Aquí se agregó la dependencia http
  json_annotation: ^4.4.0  # <-- Dependencia necesaria para json_serializable
  flutter_spinkit: ^5.1.0  # <-- Dependencia para spinner (agregada aquí)
  fluttertoast: ^8.1.2  # <-- Agregada la dependencia para usar Toasts

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.3.3  # <-- Dependencia para generar el código de json_serializable
  json_serializable: ^6.0.0  # <-- Dependencia para json_serializable

flutter:
  uses-material-design: true

  # Aquí van los assets para las imágenes y otros archivos estáticos
  assets:
    - assets/gif_libro.gif
    - assets/user_card_3.png  # <- Agrega esta línea